feat: git-url, git-default, git-name, git-owner, git-ssh tested and with completions. ready for genman

diff --git a/bin/git-url b/bin/git-url
--- a/bin/git-url
+++ b/bin/git-url
@@ -2,8 +2,6 @@
 
 set -eu
 
-# TODO: terminal con el git-url y poner pruebas de los git que he añadido y ver si hay otro git-name
-#  seguir con el puto genman, ver que hago con los git-commands si pongo directorio de git con symlinks
 #######################################
 # die with error
 # Arguments:
@@ -12,7 +10,7 @@ set -eu
 die() {
   rc=$?
   >&2 echo "${0##*/}: $*"
-  exit "${rc:-1}"
+  exit $rc
 }
 
 #######################################
@@ -24,40 +22,47 @@ die() {
 #######################################
 spec() {
   cat <<EOF
-${GIT_COMMAND} [$(git blue "ARGUMENT")] [$(git blue "FORMAT")]
-${COLOR_SCRIPT} [$(git red "<remote>")|$(git red "<owner/repo>")|$(git red "<url>")] \
-[$(git red "--file")|$(git red "--git")|$(git red "--https")|$(git red "--pip")|$(git red "--raw")|\
-$(git red "--ssh")|$(git red "--web")]
-${COLOR_SCRIPT} $(git red "<remote>")
-${COLOR_SCRIPT} $(git red "<owner/repo>")
-${COLOR_SCRIPT} $(git red "<url>")
-${COLOR_SCRIPT} $(git red "<remote>") $(git red "--ssh")
-${COLOR_SCRIPT} $(git red "<url>") $(git red "--raw")
-${COLOR_SCRIPT} $(git red "--web") $(git red "<owner/repo>")
+${GIT_COMMAND} [$(git blue "ARGUMENT")] [$(git red "FORMAT")] [$(git magenta "OPTION")]
+${COLOR_SCRIPT} [$(git blue "<remote>")|$(git blue "<owner/repo>")|$(git blue "<url>")] \
+[$(git red "--file")|$(git red "--git")|$(git red "--https")|$(git red "--insteadOf")|$(git red "--pip")|\
+$(git red "--raw")| $(git red "--ssh")|$(git red "--web")]
+${COLOR_SCRIPT} $(git blue "<remote>")
+${COLOR_SCRIPT} $(git blue "<remote>") $(git red "--insteadOf")
+${COLOR_SCRIPT} $(git blue "<owner/repo>")
+${COLOR_SCRIPT} $(git blue "<url>")
+${COLOR_SCRIPT} $(git blue "<url>") $(git magenta "--ping")
+${COLOR_SCRIPT} $(git blue "<url>") $(git magenta "--ping") $(git red "--git")
+${COLOR_SCRIPT} $(git blue "<remote>") $(git magenta "--ping") $(git red "--ssh")
+${COLOR_SCRIPT} $(git blue "<remote>") $(git red "--ssh")
+${COLOR_SCRIPT} $(git blue "<url>") $(git red "--raw")
+${COLOR_SCRIPT} $(git red "--web") $(git blue "<owner/repo>")
 ${COLOR_SCRIPT} $(git red "--pip")
 ${COLOR_SCRIPT} $(git red "--ssh")
 
-${COLOR_SCRIPT} - remote from config $(git red "<remote>"), $(git red "<url>") or \
-$(git red "<owner/repo>") (default: $(git red "origin"))
-          Valid $(git blue "ARGUMENTS"): $(git red "<remote>"), $(git red "<url>") or \
-$(git red "<owner/repo>").
-          Only one $(git blue "ARGUMENT") and/or one $(git blue "FORMAT") can be provided.
-          Any $(git blue "FORMAT") can be used for $(git red "<url>") as $(git blue "ARGUMENT").
+${COLOR_SCRIPT} - remote from config $(git blue "<remote>"), $(git blue "<url>") or \
+$(git blue "<owner/repo>") (default: $(git blue "origin"))
+          Valid $(git blue "ARGUMENTS"): $(git blue "<remote>"), $(git blue "<url>") or \
+$(git blue "<owner/repo>").
+          Only one $(git blue "ARGUMENT") and/or one $(git red "FORMAT") can be provided.
+          Any $(git red "FORMAT") can be used for $(git blue "<url>") as $(git blue "ARGUMENT").
           Default branch is used for $(git red "--raw").
           Use ${COLOR_SCRIPT} instead of ${GIT_COMMAND} when running outside a git repository \
-with an $(git blue "ARGUMENT") of type $(git red "<owner/repo>") or $(git red "<url>").
+with an $(git blue "ARGUMENT") of type $(git blue "<owner/repo>") or $(git blue "<url>").
 --
 h,help      Show help and exit.
-b,ping      Check reachability of url.
 
  $(git blue "FORMATS"):
 file!        Local url: i.e.: $(git magenta "git+file://<user>/<repo>")
-git!         $(git red "Default") url, i.e.: $(git magenta "https://github.com/<user>/<repo>.git")
+git!         $(git green "Default") url, i.e.: $(git magenta "https://github.com/<user>/<repo>.git")
 https!       HTTPS url, i.e.: $(git magenta "git+https://github.com/<user>/<repo>.git")
+insteadOf!   insteadOf url for a $(git blue "<remote>"), i.e.: $(git magenta "https://github.com/<user>/<repo>.git")
 pip!         PIP url, i.e: $(git magenta "git+ssh://git@github.com/<user>/<repo>.git")
 raw!         GitHub raw url, i.e: $(git magenta "https://raw.githubusercontent.com/<user>/<repo>/<branch>")
 ssh!         SSH url, i.e: $(git magenta "git@github.com:<user>/<repo>.git")
 web!         GitHub web url, i.e.: $(git magenta "https://github.com/<user>/<repo>")
+
+ $(git magenta "OPTIONS"):
+ping         Check reachability of url, only for $(git red "--git") and $(git red "--ssh").
 EOF
 }
 
@@ -75,64 +80,66 @@ format() {
   suffix=".git"
   case "${format:-git}" in
     --file) prefix="git+file://"; suffix="" ;;
-    --git) : ;;
+    --git|--insteadOf) : ;;
     --https) prefix="git+https://github.com/" ;;
     --pip) prefix="git+ssh://git@github.com/" ;;
-    --raw) prefix="https://raw.githubusercontent.com/"; suffix="/$(git-default "$1")" ;;
-    --ssh)  prefix="git@github.com:" ;;
+    --raw) prefix="https://raw.githubusercontent.com/"; suffix="/$(git default "$("$0" "$1")")" ;;
+    --ssh) prefix="git@github.com:" ;;
     --web) suffix="" ;;
   esac
   echo "${prefix}${owner}/${name}${suffix}"
 }
 
-# TODO: aqui lo dejo probar esto, habría que hacer un checkout default,
-#  probar url y seguir con submodule que necesita los git all y clone...
-#   copiar de semver el como calcula el tag actual
-#   Algo de si valid url, añadir un --ping aqui??? y cambiar el ping a ssh access algo mas genérico
 #######################################
 # git url
 # Globals:
 #   opt
 #######################################
 main() {
-  ping=false
-  
+  insteadOf=false
   for arg; do
     case "${arg}" in
       -h|--help) . git-parse.sh || exit ;;
+      --insteadOf)
+        [ ! "${format-}" ] || die "${arg}, ${format}: only one format can be provided"
+        insteadOf=true
+        format="${arg}"
+        ;;
       --file|--git|--https|--pip|--raw|--ssh|--web)
         [ ! "${format-}" ] || die "${arg}, ${format}: only one format can be provided"
         format="${arg}"
         ;;
-      --ping) ping=true ;;
+      --ping) ping="${arg}" ;;
       *)
-        [ ! "${format-}" ] || die "${arg}, ${format}: only one argument can be provided remote|owner/repo|url"
+        [ ! "${argument-}" ] || die "${arg}, ${argument}: only one argument can be provided <remote>|<owner/repo>|<url>"
         argument="${arg}" ;;
     esac
   done
 
-#  while test $# != 0; do
-#    case "$1" in
-#      --) shift; break ;;
-#      --*) opt="$1"  ;;
-#    esac
-#    shift
-#  done
+  argument="${argument:-origin}"
+  : "${format=--git}"
 
-  argument="${1:-origin}"
-  : "${format=git}"
-
-#  >&2 echo "opt: ${opt-}, argument: ${argument-}"
+  # shellcheck disable=SC2086,SC2046
   if echo "${argument}" | grep -q '/' || [ "${opt-}" ]; then
+    ! $insteadOf || die "${format}: cannot be used with a path"
     url="$(format "${argument}")"
   else
-    url="$(git config remote."${argument}".url)" || die Invalid Remote: "${argument}"
+    remotes="$(git remote)"
+    [ "${remotes-}" ] || die "${PWD}: no remote configured"
+    inargs "${argument}" $(git remote) || die "${PWD}: ${argument}: invalid remote"
+    if $insteadOf; then
+      url="$(git ls-remote --get-url "${argument}")"
+    else
+      url="$(git config remote."${argument}".url)"
+    fi
+
+    { [ ! "${format-}" ] || $insteadOf; } || url="$("$0" "${url}" "${format}" ${ping-})"
   fi
 
-  if $ping; then
+  if [ "${ping-}" ]; then
     case "${format}" in
-      --git|--ssh) git ls-remote "${url}" CHECK_GIT_REMOTE_URL_REACHABILITY ;;
-      *) die "--ping: can only be used with --git|--ssh" ;;
+      --git|--insteadOf|--ssh) git ls-remote "${url}" CHECK_GIT_REMOTE_URL_REACHABILITY ;;
+      *) false || die "--ping: can only be used with --git|--insteadOf|--ssh" ;;
     esac
   fi
 
